### ISSUE TITLE
conn.Close is not Idempotent

### ISSUE THREAD

**Issue by ganesh-karthick** [samuel/go-zookeeper#148]
API [conn.Close()](https://godoc.org/github.com/samuel/go-zookeeper/zk#Conn.Close)
Calling conn.Close on already closed connection causes program to panic, It would be good, if the call is made idempotent.

```
goroutine 8 [running]:
panic(0x576420, 0xc420252880)
	/home/ganeraje/Documents/devtools/go/src/runtime/panic.go:500 +0x1a1
pipeline/vendor/github.com/samuel/go-zookeeper/zk.(*Conn).Close(0xc4203ea000)
	/home/ganeraje/Documents/git/goworkspace/src/pipeline/vendor/github.com/samuel/go-zookeeper/zk/conn.go:253 +0x47
```

**Comment by mattn** [comment]
any update on this? conn.Close() is not atomic even though most of APIs are goroutine safe.
