### ISSUE TITLE
client will receive session expires error, when zk leader shut down

### ISSUE THREAD

**Issue by peanutgyz** [samuel/go-zookeeper#72]
if client connect to zk leader, then zk leader shutdown.
client will retry another zk server, connect, but then io.ReadFull will get EOF.

in zk log, find 
-07-29 15:28:09,846 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2283:NIOServerCnxnFactory@197] - Accepted socket connection from /127.0.0.1:35420
 2015-07-29 15:28:09,848 [myid:3] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2283:NIOServerCnxn@362] - Exception causing close of session 0x0 due to java.io.IOException:       ZooKeeperServer not running
 2015-07-29 15:28:09,849 [myid:3] - DEBUG [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2283:NIOServerCnxn@366] - IOException stack trace
 java.io.IOException: ZooKeeperServer not running
     at org.apache.zookeeper.server.NIOServerCnxn.readLength(NIOServerCnxn.java:931)
     at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:237)
     at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
     at java.lang.Thread.run(Thread.java:745)
 2015-07-29 15:28:09,850 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2283:NIOServerCnxn@1007] - Closed socket connection for client /127.0.0.1:35420 (no session        established for client)

zk follower shutdown , because leader down.
then in go-zookeeper client, reconnect get EOF error.

should wait a little time before reconnect ?

**Comment by osembedded** [comment]
I can confirm that I see this exact behavior in my setup when the leader dies. All of the follower ZKs close the client connections. The clients then immediately retry since go-zookeeper doesn't wait for the quorum to be established. So when this retry happens, we connect to one of the ZKs in the quorum that is running and the accepts the tcp connection and immediately closes it down.

Go-zookeeper sends a ErrSessionExpired back ( due to err: EOF in the line mentioned below.) to the application even though the ZK server did not reply back with this message.


   _, err = io.ReadFull(c.conn, buf[:4])
   c.conn.SetReadDeadline(time.Time{})
   if err != nil {
      // Sometimes zookeeper just drops connection on invalid session data,
      // we prefer to drop session and start from scratch when that event
      // occurs instead of dropping into loop of connect/disconnect attempts
      c.logger.Printf("Setting SessionExpired. Got err: %v", err)

      c.sessionID = 0
      c.passwd = emptyPassword
      c.lastZxid = 0
      c.setState(StateExpired)
      return ErrSessionExpired
   }
